title: Farmlife-Wiki
description: "Wiki für Farmlife: Badoras!"
theme: just-the-docs

url: https://wiki.badoras.life

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
