title: Farmlife-Wiki
description: "Wiki für Farmlife: Badoras!"
theme: just-the-docs

url: https://wiki.badoras.life

aux_links:
  Website: "https://badoras.life"
  Impressum: "https://badoras.life/impressum"
  Source Code: "https://github.com/FLBadoras/wiki"

aux_links_new_tab: true

color_scheme: dark


collections:
  team_members:
    name: Team Members
  commands:
    name: Commands
  tutorials:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    tutorials:
      name: Tutorials
      nav_fold: true
