name: Command ergänzen
description: Ergänze einen Command im Wiki!
title: "[COMMAND] "
labels: ["documentation","good first issue"]
body:
  - type: input
    id: command
    attributes:
      label: "Command"
      description: "Wie heißt der Command?"
      placeholder: "Beispiel: /willkommen"
    validations:
      required: true
  - type: input
    id: example
    attributes:
      label: "Beispiel"
      description: |
        Wie wird dieser Command verwendet? Bitte verwende
        geschweifte Klammern für notwendige Argumente und
        eckige Klammern für optionale Argumente.
      placeholder: "Beispiel: /willkommen [Nachricht]"
      value: "Verwendung unbekannt."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Beschreibung"
      description: "Beschreibe den Command!"
      placeholder: "Beispiel: Mit dem Command kann man eine(n) neue(n) Mitspieler(in) begrüßen. Man kann hierzu optional eine Nachricht anfügen."
      value: "Details unbekannt."
    validations:
      required: true
  - type: textarea
    id: aliases
    attributes:
      label: "Aliase"
      description: "Nenne Aliase für den Command, falls existent und bekannt."
      placeholder: "Beispiel: /konto ist ein Aliases für /geld"
      value: "Keine Aliase bekannt."
  - type: checkboxes
    id: notexists
    attributes:
      label: "Überprüfung"
      description: "Überprüfe, dass der Command noch nicht im Wiki aufgelistet wird!"
      options:
        - label: "Alle benötigten Informationen (vgl. ausgefüllte Informationen zuvor) liegen vor."
          required: false
        - label: "Der Command wird noch nicht im Wiki aufgeführt."
          required: true
        - label: "Ich habe auch überprüft, dass der Command nicht bereits über eine andere Pull Request hinzugefügt wird."
          required: false
